name: Dynamic Quote Update

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}  # Use PAT for checkout
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests
        run: pip install requests
        
      - name: Update README with new quote
        run: |
          python .github/scripts/update_quote.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'Ashish Vaghela'
          git config --global user.email 'ashishcodejourney@users.noreply.github.com'
          git add README.md
          
          # Get current date in YYYY-MM-DD format
          current_date=$(date +'%Y-%m-%d')
          
          # Check if there are changes and commit with conventional commit message
          git diff --quiet && git diff --staged --quiet || (git commit -m "content(quote): update programming wisdom [${current_date}]" && git push)
